data:
  data_location: "/fast-2/datasets/Solv4_strings_wav/audio/Violin/ordinario"
  # data_location: "/slow-2/antoine/dataset/saxo"
  extension: "wav"

preprocess:
  sampling_rate: &samplingrate 16000
  signal_length: &signallength 64000
  block_size: &blocksize 64

  oneshot: false # crop every audio file to exactly signal length
  out_dir: /fast-1/tmp/solordinario/

model:
  hidden_size: 512
  n_harmonic: 101
  n_bands: 65
  sampling_rate: *samplingrate
  block_size: *blocksize

train:
  scales: [2048, 1024, 512, 256, 128, 64]
  overlap: .75
