# DDSP CONFIGURATION FILE
training:
  batch: 16
  name: "test_violin_harmonic_hilr"
  root: "runs"
  lr: .0001
  epochs: 10000
  scales: [2048, 1024, 512, 256, 128, 64]

data:
  sampling_rate: &sr 16000
  block_size: &block_size 160
  signal_size: 64000
  preprocessed: "/fast-1/tmp/johngarner/"
  wav_loc: "/slow-2/antoine/johngarner/"

recurrent_args:
  n_inputs: 2
  hidden_size: &feature_out 512
  n_outputs: 3
  n_layers: 3

harmonic_args:
  sampling_rate: *sr
  upsampling: *block_size
  n_harmonic: 101

noise_args:
  sampling_rate: *sr
  upsampling: *block_size
  n_band: 65
