# DDSP CONFIGURATION FILE
training:
  batch: 16
  name: "test_violin"
  root: "runs"
  lr: .0001
  epochs: 1000
  scales: [2048, 1024, 512, 256, 128, 64]

data:
  sampling_rate: &sr 24000
  block_size: &block_size 256
  signal_size: 32768
  preprocessed: "/fast-1/tmp/ddsp_violin/"
  wav_loc: "/fast-2/datasets/Solv4_strings_wav/audio/Violin/"

recurrent_args:
  n_inputs: 2
  hidden_size: &feature_out 512
  n_outputs: 3
  n_layers: 3

harmonic_args:
  feature_out: *feature_out
  n_harmonic: 101
  upsample_factor: *block_size
  sampling_rate: *sr

noise_args:
  feature_out: *feature_out
  n_band: 65
  upsample_factor: *block_size
  sampling_rate: *sr
