# DDSP CONFIGURATION FILE

data:
  sampling_rate: &sr 24000
  block_size: &block_size 256

recurrent_args:
  n_inputs: 2
  hidden_size: &feature_out 512
  n_outputs: 3
  n_layers: 3

harmonic_args:
  feature_out: *feature_out
  n_harmonic: 101
  upsample_factor: *block_size
  sampling_rate: *sr

noise_args:
  feature_out: *feature_out
  n_band: 65
  upsample_factor: *block_size
  sampling_rate: *sr
