# DDSP CONFIGURATION FILE
training:
  batch: 16
  name: "test_violin_harmonic_hilr"
  root: "runs"
  lr: .001
  epochs: 10000
  scales: [2048, 1024, 512, 256, 128, 64]

data:
  sampling_rate: &sr 16000
  block_size: &block_size 160
  signal_size: 64000
  # preprocessed: "/fast-1/tmp/johngarner/"
  preprocessed: "/fast-1/tmp/harm/"
  # wav_loc: "/slow-2/antoine/johngarner/"
  wav_loc: "/slow-2/antoine/harm/"

recurrent_args:
  n_inputs: 2
  hidden_size: &feature_out 512
  n_outputs: 3
  n_layers: 3

harmonic_args:
  feature_out: *feature_out
  n_harmonic: 101
  upsample_factor: *block_size
  sampling_rate: *sr

noise_args:
  feature_out: *feature_out
  n_band: 65
  upsample_factor: *block_size
  sampling_rate: *sr
